config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'images#index'

  resources :images
  resources :tags

  post 'taggings', to: 'images#taggings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :file, ImageUploader

  belongs_to :user
  has_many :image_tags, dependent: :destroy
  has_many :tags, through: :image_tags
  validates :name, presence: true
  validates :file, file_size: { less_than_or_equal_to: 1.megabytes },
                   file_content_type: { allow: ['image/jpeg', 'image/png', 'image/gif'] }

  scope :sort_by_name_asc, -> { order(name: :asc) }
  scope :sort_by_name_desc, -> { order(name: :desc) }
  scope :search_by, ->(keyword) { where('LOWER(name) LIKE ?', "%#{keyword}%") }

  def self.add_pagenation(param)
    page(param).per(10)
  end

  def self.sort_by_order(order)
    order == 'desc' ? sort_by_name_desc : sort_by_name_asc
  end
end

app/models/image_tag.rb
class ImageTag < ApplicationRecord
  belongs_to :image
  belongs_to :tag
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :image_tags, dependent: :destroy
  has_many :images, through: :image_tags
  validates :name, presence: true

  scope :sort_by_name_asc, -> { order(name: :asc) }
  scope :sort_by_name_desc, -> { order(name: :desc) }
  scope :search_by, ->(keyword) { where('LOWER(name) LIKE ?', "%#{keyword}%") }

  def self.names_downcased
    sort_by_name_asc.map { |tag| tag.name.downcase }
  end

  def images_sort_by(order)
    order == 'asc' ? images.sort_by_name_asc : images.sort_by_name_desc
  end

  def images_search_by(keyword)
    images unless keyword

    images.search_by(keyword) || images
  end

  def self.add_pagenation(param)
    page(param).per(10)
  end

  def self.sort_by_order(order)
    order == 'desc' ? sort_by_name_desc : sort_by_name_asc
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :images, dependent: :destroy
  has_many :tags, dependent: :destroy
  has_many :image_tags, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def images_sort_by(order)
    order == 'asc' ? images.sort_by_name_asc : images.sort_by_name_desc
  end

  def tags_num
    tags.count
  end

  def tags_sort_by(order)
    order == 'asc' ? tags.sort_by_name_asc : tags.sort_by_name_desc
  end

  def images_search_by(keyword)
    images unless keyword

    images.search_by(keyword) || images
  end

  def tags_search_by(keyword)
    tags unless keyword

    tags.search_by(keyword) || tags
  end

  def find_image_tags(tag_id, image_id)
    image_tags.where(tag_id: tag_id, image_id: image_id)[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @tags = current_user.tags
    @order = params[:sort_by] || 'asc'
    @keyword = params[:search] ? params[:search].strip.downcase : ''
    @images = current_user.images_search_by(@keyword).sort_by_order(@order).add_pagenation(params[:page])
  end

  # GET /images/1 or /images/1.json
  def show; end

  # GET /images/new
  def new
    @image = current_user.images.new
  end

  # GET /images/1/edit
  def edit
    @image.file.cache! unless @image.file.blank?
  end

  # POST /images or /images.json
  def create
    @image = current_user.images.new(image_params)
    respond_to do |format|
      if @image.save
        @status = 'success'
        format.js { flash[:notice] = 'Image was successfully created.' }
      else
        @status = 'fail'
        @image.errors.full_messages.each do |msg|
          format.js { flash[:alert] = msg }
        end
      end
    end
  end

  def taggings
    @keywords = params[:keywords].uniq
    @keywords.each_with_index do |keyword, index|
      tag = Tag.find_by(name: keyword) || current_user.tags.create(name: keyword)
      current_user.image_tags.create(image_id: params[:imageid], tag_id: tag.id)
      break if index > 9
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params) && params[:image][:file]
        remove_current_tags(@image)
        @status = 'success'
        format.js { flash[:notice] = 'Image was successfully updated.' }
      elsif @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        @status = 'fail'
        @image.errors.full_messages.each do |msg|
          format.js { flash[:alert] = msg }
        end
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = current_user.images.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:name, :file, :file_cache, :search, :sort_by, :keywords, :imageid)
  end

  def remove_current_tags(image)
    image.tags.each do |tag|
      image_tag = current_user.find_image_tags(tag.id, image.id)
      image_tag&.destroy
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[show edit update destroy]

  # GET /tags or /tags.json
  def index
    @order = params[:sort_by] || 'asc'
    @keyword = params[:search] ? params[:search].strip.downcase : ''
    @tags = current_user.tags_search_by(@keyword).sort_by_order(@order).add_pagenation(params[:page])
  end

  # GET /tags/1 or /tags/1.json
  def show
    @order = params[:sort_by] || 'asc'
    @keyword = params[:search] ? params[:search].strip.downcase : ''
    @tag_images = @tag.images_search_by(@keyword).sort_by_order(@order).add_pagenation(params[:page])
  end

  # GET /tags/new
  def new
    @tag = current_user.tags.new
  end

  # GET /tags/1/edit
  def edit; end

  # POST /tags or /tags.json
  def create
    @tag = current_user.tags.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = current_user.tags.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tag_params
    params.require(:tag).permit(:name, :search, :sort_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_images_num(tag)
    tag.images.count
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def file_size(image)
    (image.file.size / 1000).floor(1)
  end

  def image_tags_list(image)
    image.tags.pluck(:name)
  end

  def image_tags_num(image)
    image.tags.count
  end

  def all_images_num(images)
    images.count
  end

  def file_required(type)
    type == 'Upload'
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/common/_search.html.erb
<div>this is search</div>
<form class="d-flex">
  <input type="text" class="form-control py-2 px-3" id="sarch-keywords" aria-describedby="searchKeywords" placeholder="Search">
  <button type="submit" class="btn btn-light bg-white rounded border d-flex justify-content-center align-items-center">
    <%= fa_icon 'search' %>
  </button>
</form>

app/views/images/_form.html.erb
<%= render "shared/errors", obj: image %>

<%= new_form = form_with model: image, multipart: true, local: false do |form| %>
  <div class="mb-md-5">
    <%= form.label 'Title', {class: "form-label"} %>
    <%= form.text_field :name,
    required: true,
    class: 'form-control font-20 rounded-x',
    placeholder: 'Sydney Opera House' %>
  </div>

  <div class="mb-md-5">
    <%= form.label 'Image', { class: "form-label" } %><br>

    <% if image.file.url %>
      <img src="<%= image.file.url %>" alt="<%= image.name %>" class="image form-image rounded-x d-block text-center m-auto mb-5">
    <% end %>

    <div class="fallback">
      <p>
        <span class="desc">Drop an image here or<br><span class="underline">Browse from your computer</span></span>
        <%= fa_icon "picture-o" %>
      </p>
      <%= form.file_field :file, class: 'dropzone', required: file_required(btn_msg) %>
    </div>

    <%= form.hidden_field :file_cache %>
  </div>

  <div class="mb-md-5">
    <%= form.submit btn_msg, class: 'btn btn-dark font-16 float-end p-3 rounded-x shadow-x', id: 'update-image' %>
  </div>
<% end %>

<%= javascript_pack_tag 'parts/form' %>

app/views/images/_image.html.erb
<tr>
  <td class="flex-image-td">
    <div class="d-flex justify-content-end">
      <img src="<%= image.file.url %>" alt="<%= image.name %>" class="images ms-auto">
    </div>
  </td>
  <td>
    <div class="fw-bold font-20"><%= image.name %></div>
    <div class="font-14"><%= file_size(image) %> KB</div>
  </td>
  <td>
    <% if image.tags %>
      <%= render partial: "tags/tag", collection: image_tags_list(image) %>
    <% end %>
  </td>
  <td class="text-center">
    <%= image_tags_num(image) %>
  </td>
  <td>
    <%= render partial: "shared/actions", locals: { model: image, edit_path: edit_image_path(image) } %>
  </td>
</tr>

app/views/images/_images.html.erb
<div class="table-responsive mb-5 pb-10">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col" class="fw-bold">
          <% if current == 'images' %>
            <%= render 'images/sort', order: @order %>
          <% elsif current == 'tag_images' %>
            <%= render partial: 'tags/sort', locals: { order: @order, tag: tag } %>
          <% end %>
        </th>
        <th scope="col">Tags</th>
        <th scope="col" class="text-center">Total Tags</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "images/image", collection: images %>
    </tbody>
  </table>
</div>

app/views/images/_new.html.erb
<div class="modal-dialog" role="document" id="modal">
  <div class="modal-content">
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    <h1 class="text-center">Upload Image</h1>
    <%= render partial: "form", locals: { btn_msg: 'Upload', image: @image } %>
  </div>
</div>

app/views/images/_sort.html.erb
<% if order == 'desc' %>
  <%= link_to images_path(sort_by: 'asc'), class: 'sort-by-name' do %>
    Name <%= fa_icon "chevron-up" %>
  <% end %>
<% else %>
  <%= link_to images_path(sort_by: 'desc'), class: 'sort-by-name' do %>
    Name <%= fa_icon "chevron-down" %>
  <% end %>
<% end %>

app/views/images/create.js.erb
<% if @status == 'success' %>
const spinner = document.getElementById('loading-spinner')
const body = document.querySelector('body')
spinner.classList.add('show')
body.classList.add('loading')

const raw = JSON.stringify({
  user_app_id: {
    user_id: '<%= ENV['CLARIFY_USER_ID'] %>',
    app_id: '<%= ENV['CLARIFY_APP_ID'] %>',
  },
  inputs: [
    {
      data: {
        image: {
          url: '<%= @image.file %>',
        },
      },
    },
  ],
});

const requestOptions = {
  method: 'POST',
  headers: {
    Accept: 'application/json',
    Authorization: 'Key ' + '<%= ENV['CLARIFY_ACCESS_TOKEN'] %>',
  },
  body: raw,
};

fetch(
  'https://api.clarifai.com/v2/models/9f54c0342741574068ec696ddbebd699/outputs',
  requestOptions,
)
  .then((response) => response.text())
  .then((result) => {
    const data = JSON.parse(result, null, 2).outputs[0].data.regions.map(
      (item) => item.data.concepts[0].name,
    );
    console.log(data)

    $.ajax({
      url: 'taggings',
      type: 'POST',
      async: true,
      data: {
        keywords: data,
        imageid: '<%= @image.id %>'
      },
      dataType: 'html',
      success: function (data) {
        window.location.replace("<%= image_path(@image) %>");
        spinner.classList.remove('show')
        body.classList.remove('loading')
      },
      error: function (data) {
        window.location.replace("<%= images_path %>");
        spinner.classList.remove('show')
        body.classList.remove('loading')
      }
    });

  })
  .catch((error) => console.log('error', error));
<%  elsif @status == 'fail' %>
    window.location.replace("<%= images_path %>");
<% end %>
$("#modal-container").modal("hide");

app/views/images/edit.html.erb
<div class="container-lg bg-white rounded-x shadow-x p-80 max-width-medium">
  <h1 class="text-center">Editing Image</h1>
  <%= render partial: "form", locals: { btn_msg: 'Update', image: @image } %>
</div>

app/views/images/index.html.erb
<div id="modal-container"></div>
<div class="bg-white rounded-x shadow-x pb-5">
  <div class="p-7">
    <div class="heading d-flex align-items-center mb-5">
      <h1 class="me-3 fw-normal">Images</h1>
      <%= link_to new_image_path, remote: true, class:"add-item-icon shadow-x d-flex justify-content-center align-items-center text-dark ms-3" do %>
        <%= fa_icon "plus" %>
      <% end %>
    </div>
    <div class="header-tags mb-5 d-flex gap-16">
        <%= link_to images_path, class: 'btn btn-light shadow-x bg-white rounded-50 font-16 py-md-3 px-md-4 fw-bold' do %>
          ALL (<%= current_user.tags_num %>)
        <% end %>
      <% @tags.each do |tag| %>
        <%= link_to tag_path(tag), class: 'btn btn-light shadow-x bg-white rounded-50 font-16 py-md-3 px-md-4' do %>
          <%= tag.name  %> (<%= tag_images_num(tag) %>)
        <% end %>
      <% end %>
    </div>
    <%= render "shared/search", path: images_path %>
  </div>
  <%= render partial: "images/images", locals: { images: @images, current: 'images' } %>
  <%= paginate @images %>
</div>

app/views/images/new.js.erb
$("#modal-container").html("<%= escape_javascript(render 'images/new.html.erb') %>")
$("#modal-container").modal("show")

app/views/images/show.html.erb
<div class="container-lg bg-white rounded-x shadow-x">
  <div class="p-7 pb-5">
    <div class="heading d-flex align-items-center">
      <h1 class="me-3 fw-normal">Images / <%= @image.name %></h1>
    </div>
  </div>

  <div class="show-container p-7 pt-0 d-md-flex gap-20">
    <div class="show-container__image mb-5 mb-md-0">
      <img src="<%= @image.file.url %>" alt="<%= @image.name %>" class="image rounded-x">
    </div>

    <div class="show-container__text">
      <h2><%= @image.name %></h2>
      <div class="show-container__image-size mb-3">
        <%= file_size(@image) %> KB
      </div>

      <div class="d-flex gap-16 mb-4">
        <%= link_to 'Edit', edit_image_path(@image), class: 'btn btn-light bg-white shadow-x rounded-x font-16' %>
        <%= link_to image_path(@image), method: :delete, class: 'btn btn-light bg-white shadow-x rounded-x font-16' do %>
          <%= fa_icon "trash" %> Delete
        <% end %>
      </div>

      <div class="show-container__tags">
        <div>Tags</div>
        <%= render partial: "tags/tag", collection: image_tags_list(@image) %>
      </div>
    </div>
  </div>
</div>

app/views/images/update.js.erb
<% if @status == 'success' %>
const spinner = document.getElementById('loading-spinner')
const body = document.querySelector('body')
spinner.classList.add('show')
body.classList.add('loading')

const raw = JSON.stringify({
  user_app_id: {
    user_id: '<%= ENV['CLARIFY_USER_ID'] %>',
    app_id: '<%= ENV['CLARIFY_APP_ID'] %>',
  },
  inputs: [
    {
      data: {
        image: {
          url: '<%= @image.file %>',
        },
      },
    },
  ],
});

const requestOptions = {
  method: 'POST',
  headers: {
    Accept: 'application/json',
    Authorization: 'Key ' + '<%= ENV['CLARIFY_ACCESS_TOKEN'] %>',
  },
  body: raw,
};

fetch(
  'https://api.clarifai.com/v2/models/9f54c0342741574068ec696ddbebd699/outputs',
  requestOptions,
)
  .then((response) => response.text())
  .then((result) => {
    const data = JSON.parse(result, null, 2).outputs[0].data.regions.map(
      (item) => item.data.concepts[0].name,
    );
    console.log(data)

    $.ajax({
      url: '/taggings',
      type: 'POST',
      async: true,
      data: {
        keywords: data,
        imageid: '<%= @image.id %>'
      },
      dataType: 'html',
      success: function (data) {
        window.location.replace("<%= image_path(@image) %>");
        spinner.classList.remove('show')
        body.classList.remove('loading')
      },
      error: function (data) {
        window.location.replace("<%= images_path %>");
        spinner.classList.remove('show')
        body.classList.remove('loading')
      }
    });

  })
  .catch((error) => console.log('error', error));
<%  elsif @status == 'fail' %>
    window.location.replace("<%= edit_image_path(@image) %>");
<% end %>
$("#modal-container").modal("hide");

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid mx-3">
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag('BowerBird.svg', class: 'main-logo') %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="justify-content-end collapse navbar-collapse" id="navbarScroll">
        <%= link_to images_path, class: "nav-link d-flex align-items-center text-white" do %>
          <%= fa_icon "image", class: 'me-1' %>Images
        <% end %>
        <%= link_to tags_path, class: "nav-link d-flex align-items-center text-white" do %>
          <%= fa_icon "hashtag" %> Tags
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class: "nav-link d-flex align-items-center text-white" do %>
          <%= fa_icon "sign-out" %> Sign Out
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class='alert alert-success mt-3 mb-5'>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class='alert alert-danger mt-3 mb-5'>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_spinner.html.erb
<div id="loading-spinner" class="loading-spinner">
  <div class="spinner-grow text-info loading-spinner__circle" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal Library :BowerTest</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/spinner"  %>
    <%= render  "layouts/header" %>
    <main class="container-fluid bg-light p-5">
      <%= render  "layouts/messages" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_actions.html.erb
<ul class="navbar-nav actions-menu">
  <li class="dropdown">
    <a class="nav-link dropdown-toggle text-dark rounded-x shadow-x" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Actions <%= fa_icon "ellipsis-v", class: 'me-1' %>
    </a>
    <ul class="dropdown-menu rounded-x shadow-x border-0">
      <li><%= link_to 'View', model, class: 'dropdown-item' %></li>
      <li><%= link_to 'Edit', edit_path, class: 'dropdown-item' %></li>
      <li><%= link_to 'Delete', model, method: :delete, data: { confirm: 'Are you sure?' }, class: 'dropdown-item' %></li>
    </ul>
  </li>
</ul>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_search.html.erb
<%= form_tag(path, method: "get", class: "form") do %>
 <div class="d-flex gap-16">
  <%= text_field_tag 'search', nil, class: 'form-control py-2 px-3 search-form__input border-0 shadow-x rounded-x', placeholder: 'Search' %>
  <%= button_tag type: 'submit', class: 'btn btn-light bg-white rounded-x border-0 shadow-x d-flex justify-content-center align-items-center search-form__button' do %>
    <%= fa_icon "search" %>
  <% end %>
 </div>
<% end %>

app/views/tags/_form.html.erb
<%= render "shared/errors", obj: tag %>

<%= form_with(model: tag) do |form| %>
  <div class="mb-5">
    <%= form.label 'Tag Title', {class: "form-label"} %>
    <%= form.text_field :name, required: true, class: 'form-control font-20 rounded-x' %>
  </div>

  <div class="mb-5">
    <%= form.submit 'Add Tag', class: 'btn btn-dark font-16 float-end p-3 rounded-x shadow-x' %>
  </div>
<% end %>

app/views/tags/_sort.html.erb
<% if order == 'desc' %>
  <%= link_to tag_path(id: tag.id, sort_by: 'asc'), class: 'sort-by-name' do %>
    Name <%= fa_icon "chevron-up" %>
  <% end %>
<% else %>
  <%= link_to tag_path(id: tag.id, sort_by: 'desc'), class: 'sort-by-name' do %>
    Name <%= fa_icon "chevron-down" %>
  <% end %>
<% end %>

app/views/tags/_tag.html.erb
<span class="badge bg-light text-dark font-16"><%= tag %></span>

app/views/tags/_tags.html.erb
<div class="table-responsive mb-5 pb-10">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col" class="fw-bold ps-5">
          <% if @order == 'desc' %>
            <%= link_to tags_path(sort_by: 'asc'), class: 'sort-by-name' do %>
              Tag <%= fa_icon "chevron-up" %>
            <% end %>
          <% else %>
            <%= link_to tags_path(sort_by: 'desc'), class: 'sort-by-name' do %>
              Tag <%= fa_icon "chevron-down" %>
            <% end %>
          <% end %>
        </th>
        <th scope="col" class="text-center">Total Images</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% tags.each do |tag| %>
          <tr>
            <td></td>
            <td class="ps-5">
              <div class="fw-bold font-20"><%= tag.name %></div>
            </td>
            <td class="text-center">
              <%= tag_images_num(tag) %>
            </td>
            <td class="d-flex justify-content-end">
              <%= render partial: "shared/actions", locals: { model: tag, edit_path: edit_tag_path(tag) } %>
            </td>
            <td></td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/tags/edit.html.erb
<div class="container-lg bg-white rounded-x shadow-x p-80 max-width-medium">
  <h1 class="text-center">Editing Tag</h1>
  <%= render 'form', tag: @tag %>
</div>

app/views/tags/index.html.erb
<div class="bg-white rounded-x shadow-x pb-5">
  <div class="p-7">
    <div class="heading d-flex align-items-center mb-5">
      <h1 class="me-3 fw-normal">Tags</h1>
      <%= link_to new_tag_path, class:"add-item-icon shadow-x d-flex justify-content-center align-items-center text-dark ms-3" do %>
        <%= fa_icon "plus" %>
      <% end %>
    </div>
    <%= render "shared/search", path: tags_path %>
  </div>
  <%= render "tags/tags", tags: @tags %>
  <%= paginate @tags %>
</div>

app/views/tags/new.html.erb
<div class="container-lg bg-white rounded-x shadow-x p-80 max-width-medium">
  <h1 class="text-center">New Tag</h1>
  <%= render 'form', tag: @tag %>
</div>

app/views/tags/show.html.erb
<div class="bg-white rounded-x shadow-x pb-5">
  <div class="p-7">
    <div class="heading d-flex align-items-center mb-5">
      <h1 class="me-3 fw-normal">Tags / <%= @tag.name %></h1>
      <%= link_to new_tag_path, class:"add-item-icon shadow-x d-flex justify-content-center align-items-center text-dark ms-3" do %>
        <%= fa_icon "plus" %>
      <% end %>
    </div>
    <%= render "shared/search", path: tag_path(@tag) %>
  </div>
  <%= render partial: "images/images", locals: { images: @tag_images, tag: @tag, current: 'tag_images' } %>
  <%= paginate @tag_images %>
</div>